# Generated by Django 5.0.6 on 2024-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('weather', models.CharField(max_length=250, verbose_name='Weather')),
                ('description', models.TextField(verbose_name='Description')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('feels_like', models.FloatField(verbose_name='Feels like')),
                ('wind_speed', models.FloatField(verbose_name='Wind speed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
