# Generated by Django 5.0.6 on 2024-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'verbose_name': 'Weather Data', 'verbose_name_plural': 'Weather Data'},
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of request'),
        ),
    ]
